name: GitHub Actions Demo
on: [push]
jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Olá, ${{ github.event_name }} GitHub Actions'
      - run: echo 'Olá, GitHub ${{ runner.os }} Actions'
      - run: echo 'Olá, GitHub Actions ${{ github.ref }} - ${{ github.repository }}'
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo 'Olá, GitHub ${{ github.repository }} Actions'
      - name: List files in the repositpry
      - run: ls ${{ github.repository }}
      - run: echo 'Olá, GitHub ${{ job.status }} Actions'
