name: Desafio Analista de Teste
on: [push]
jobs:
  rspec-with-ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout on repository
      - uses: actions/checkout@v2
        
      - name: Setup Ruby
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          
      - name: Install depedencies
      - run: bundle install
      
      - name: Running Tests Integration
      - run: bundle exec rspec
