name: Projeto QA Yapay

on: [push]

jobs:
  rspec-with-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: bundle install
      - run: bundle exec rspec