name: Projeto QA Yapay

on: 
  push: 
    branch: [master, develop]
  pull_request:
    branch: master

jobs:
  rspec-with-ruby:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
      - run: bundle install
      - run: rubocop -a test/
      - run: rubocop -A test/
